### ISSUE TITLE
Error no module named 'RollingStandardScaler'

### ISSUE THREAD

**Issue by ken2190** [nateemma/strategies#1]
https://github.com/nateemma/strategies/blob/3c72ee716066fe26c43ad7de41d73c65d6444a6d/binance/FBB_KalmanSIMD.py#L38
i got error when dryrun: no module named 'RollingStandardScaler' and no module named 'RollingStandardScaler'. Which package should be installed for this strat?

**Comment by nateemma** [comment]
sorry, I missed this. That class should be in the same directory. It's obsolete now though, sorry.

**Comment by Yeboster** [comment]
Hello, regarding import issues, I now get `No module named 'RollingKalmanSIMD'` and there's no file with that name in the current HEAD. Where should I get it?

**Comment by nateemma** [comment]
sorry, just saw this. This is pretty old code that I (thought I) replaced
long ago -looks like I missed a version of that file. Which exchange
directory are you using? binance?

As an aside, the Rolling*.py files didn't work very well, so I converted to
using just a normal rolling window.

Cheers,

Phil

**Comment by nateemma** [comment]
OK, I did leave old versions in the exchange directory. The most recent
version is in the strategies/archived directory.

I'm in the middle of a big re-write, but I'll update those directories when
I have the code stable enough to push.

Also, I could never get the simdkalman code to predict properly - it just
returns the last real value as the prediction. The other kalman lib
(pykalman) does work (but is much slower).

Are you looking at this because you are interested in Kalman filtering? If
you are comparing strat performance, the DWT versions perform better and
are faster

Cheers,

Phil
