### ISSUE TITLE
NNTC Model loading issue

### ISSUE THREAD

**Issue by Hassffw** [nateemma/strategies#47]
I'm running NNTC (any) and get the following error:
ORDI/USDT
    holds:862 (86.20%) buys:78 (7.80%) sells:60 (6.00%)
    predicting buys/sells...
    Loading existing model (/xoot/freqtrade/user_data/strategies/NNTC/models/NNTC_bbw_LSTM/NNTC_bbw_LSTM.keras)...
     Layer 'lstm_cell' expected 3 variables, but received 0 variables during loading. Expected: ['lstm/lstm_cell/kernel:0', 'lstm/lstm_cell/recurrent_kernel:0', 'lstm/lstm_cell/bias:0']
    Error loading model from /xoot/freqtrade/user_data/strategies/NNTC/models/NNTC_bbw_LSTM/NNTC_bbw_LSTM.keras. Check whether model format changed
    ERR: no model for predictions
   
Might it be the keras version ? I am using UBUNTU 20.04. My keras version is 2.15.0. Thank you

**Comment by nateemma** [comment]
No, the error means that the model it is loading doesn't match the data you
are trying to predict. I get the same error, so I probably updated the code
and didn't regenerate the model. I'll take a look and - it's been a while
since I've tested those strategies, so they may need some updating

Cheers,

Phil

**Comment by nateemma** [comment]
OK, I regenerated the model and it is now in the github repo

Cheers,

Phil

**Comment by Hassffw** [comment]
Already running ! Thank you very much, Phil.
Superfast delivery 5 stars 🥇
